### ISSUE TITLE
Syntax in Paragraphs 3 and 4, Content in Paragraph 5

### ISSUE THREAD

**Issue by comptonb37** [Mitchello457/about-me#1]
2641d32 was a nearly flawless edit of your about me section, but I noticed a couple of simple errors that could use attention. In paragraph 3, the sentence where you talk about being ahead in your math courses contains the line "and was breezed through all of his classes." I would recommend removing the word "with" from the sentence. Also, in paragraph 4, you wrote "Mitchell wanted to attended to the 2010 National Boy Scout Jamboree at Fort A.P. Hill in Virginia." I believe you meant "Mitchell wanted to attend the 2010..." but if you didn't then I'd advise changing it somehow to show how much you wanted to go. The last thing I noticed was in the paragraph about your admission to Allegheny you mentioned the amount of money you achieved through scholarships. I think this would be best left out as it is personal information that you may not want to enclose on the internet.

**Comment by Mitchello457** [comment]
Thank you for the feedback. I have addressed each issue that you have brought up.
